version: '3.8'

services:
  web:
    build: .
    ports:
      - "5017:5000"
    volumes:
      - .:/app
      - ./docs:/app/docs
      - ./data:/app/data
    env_file:
      - .env
    command: python /app/src/app.py
